# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import main_window_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 622)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabs = QTabWidget(self.centralwidget)
        self.tabs.setObjectName(u"tabs")
        self.tabs.setGeometry(QRect(10, 10, 671, 541))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 651, 501))
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.tabs.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 301, 201))
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.tabs.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 10, 371, 281))
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.tabs.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.textBrowser = QTextBrowser(self.tab_3)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 10, 651, 491))
        self.tabs.addTab(self.tab_3, "")
        self.torque_tab = QWidget()
        self.torque_tab.setObjectName(u"torque_tab")
        self.torques_label = QLabel(self.torque_tab)
        self.torques_label.setObjectName(u"torques_label")
        self.torques_label.setGeometry(QRect(10, 10, 651, 481))
        self.tabs.addTab(self.torque_tab, "")
        self.omega_tab = QWidget()
        self.omega_tab.setObjectName(u"omega_tab")
        self.omegas_label = QLabel(self.omega_tab)
        self.omegas_label.setObjectName(u"omegas_label")
        self.omegas_label.setGeometry(QRect(10, 10, 651, 481))
        self.tabs.addTab(self.omega_tab, "")
        self.inputs_tab = QTabWidget(self.centralwidget)
        self.inputs_tab.setObjectName(u"inputs_tab")
        self.inputs_tab.setGeometry(QRect(680, 10, 461, 541))
        self.ctc_tab = QWidget()
        self.ctc_tab.setObjectName(u"ctc_tab")
        self.groupBox = QGroupBox(self.ctc_tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 441, 331))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 20, 131, 301))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 121, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 16, 16))
        self.rod_mount_x_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_x_ctc.setObjectName(u"rod_mount_x_ctc")
        self.rod_mount_x_ctc.setGeometry(QRect(20, 50, 101, 22))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 16, 16))
        self.rod_mount_y_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_y_ctc.setObjectName(u"rod_mount_y_ctc")
        self.rod_mount_y_ctc.setGeometry(QRect(20, 80, 101, 22))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 16, 16))
        self.rod_mount_z_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_z_ctc.setObjectName(u"rod_mount_z_ctc")
        self.rod_mount_z_ctc.setGeometry(QRect(20, 110, 101, 22))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 140, 121, 16))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 220, 16, 16))
        self.motor_y = QLineEdit(self.groupBox_3)
        self.motor_y.setObjectName(u"motor_y")
        self.motor_y.setGeometry(QRect(20, 190, 101, 22))
        self.motor_z = QLineEdit(self.groupBox_3)
        self.motor_z.setObjectName(u"motor_z")
        self.motor_z.setGeometry(QRect(20, 220, 101, 22))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 160, 16, 16))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 190, 16, 16))
        self.motor_x = QLineEdit(self.groupBox_3)
        self.motor_x.setObjectName(u"motor_x")
        self.motor_x.setGeometry(QRect(20, 160, 101, 22))
        self.motor_angle = QLineEdit(self.groupBox_3)
        self.motor_angle.setObjectName(u"motor_angle")
        self.motor_angle.setGeometry(QRect(20, 270, 101, 22))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 250, 121, 16))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(150, 20, 131, 301))
        self.ctc_length = QLineEdit(self.groupBox_4)
        self.ctc_length.setObjectName(u"ctc_length")
        self.ctc_length.setGeometry(QRect(20, 50, 101, 22))
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 30, 121, 16))
        self.ctc_neutral_angle = QLineEdit(self.groupBox_4)
        self.ctc_neutral_angle.setObjectName(u"ctc_neutral_angle")
        self.ctc_neutral_angle.setGeometry(QRect(20, 100, 101, 22))
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 80, 121, 16))
        self.ctc_rotation = QLineEdit(self.groupBox_4)
        self.ctc_rotation.setObjectName(u"ctc_rotation")
        self.ctc_rotation.setGeometry(QRect(20, 150, 101, 22))
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 130, 121, 16))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 180, 121, 16))
        self.motor_torque_ctc = QLineEdit(self.groupBox_4)
        self.motor_torque_ctc.setObjectName(u"motor_torque_ctc")
        self.motor_torque_ctc.setGeometry(QRect(20, 200, 101, 22))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 230, 121, 16))
        self.motor_rpm_ctc = QLineEdit(self.groupBox_4)
        self.motor_rpm_ctc.setObjectName(u"motor_rpm_ctc")
        self.motor_rpm_ctc.setGeometry(QRect(20, 250, 101, 22))
        self.groupBox_13 = QGroupBox(self.ctc_tab)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 340, 441, 161))
        self.label_38 = QLabel(self.groupBox_13)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 30, 121, 16))
        self.label_41 = QLabel(self.groupBox_13)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 60, 101, 20))
        self.zx_rodmount_angle_ctc = QLineEdit(self.groupBox_13)
        self.zx_rodmount_angle_ctc.setObjectName(u"zx_rodmount_angle_ctc")
        self.zx_rodmount_angle_ctc.setEnabled(False)
        self.zx_rodmount_angle_ctc.setGeometry(QRect(170, 30, 61, 22))
        self.zx_pushrod_angle_ctc = QLineEdit(self.groupBox_13)
        self.zx_pushrod_angle_ctc.setObjectName(u"zx_pushrod_angle_ctc")
        self.zx_pushrod_angle_ctc.setEnabled(False)
        self.zx_pushrod_angle_ctc.setGeometry(QRect(170, 60, 61, 22))
        self.label_42 = QLabel(self.groupBox_13)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 90, 201, 20))
        self.xy_rodmount_pushrod_angle_ctc = QLineEdit(self.groupBox_13)
        self.xy_rodmount_pushrod_angle_ctc.setObjectName(u"xy_rodmount_pushrod_angle_ctc")
        self.xy_rodmount_pushrod_angle_ctc.setEnabled(False)
        self.xy_rodmount_pushrod_angle_ctc.setGeometry(QRect(170, 90, 61, 22))
        self.button_calc_ctc = QPushButton(self.groupBox_13)
        self.button_calc_ctc.setObjectName(u"button_calc_ctc")
        self.button_calc_ctc.setGeometry(QRect(370, 90, 61, 24))
        self.min_ctc_pushrod_angle = QLineEdit(self.groupBox_13)
        self.min_ctc_pushrod_angle.setObjectName(u"min_ctc_pushrod_angle")
        self.min_ctc_pushrod_angle.setEnabled(False)
        self.min_ctc_pushrod_angle.setGeometry(QRect(370, 60, 61, 22))
        self.label_44 = QLabel(self.groupBox_13)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(240, 60, 131, 16))
        self.label_45 = QLabel(self.groupBox_13)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(240, 30, 131, 16))
        self.max_ctc_pushrod_angle = QLineEdit(self.groupBox_13)
        self.max_ctc_pushrod_angle.setObjectName(u"max_ctc_pushrod_angle")
        self.max_ctc_pushrod_angle.setEnabled(False)
        self.max_ctc_pushrod_angle.setGeometry(QRect(370, 30, 61, 22))
        self.inputs_tab.addTab(self.ctc_tab, "")
        self.la_tab = QWidget()
        self.la_tab.setObjectName(u"la_tab")
        self.groupBox_8 = QGroupBox(self.la_tab)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 0, 441, 281))
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 20, 131, 251))
        self.label_24 = QLabel(self.groupBox_9)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 121, 16))
        self.label_25 = QLabel(self.groupBox_9)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 50, 16, 16))
        self.rod_mount_x_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_x_linear.setObjectName(u"rod_mount_x_linear")
        self.rod_mount_x_linear.setGeometry(QRect(20, 50, 101, 22))
        self.label_26 = QLabel(self.groupBox_9)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 80, 16, 16))
        self.rod_mount_y_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_y_linear.setObjectName(u"rod_mount_y_linear")
        self.rod_mount_y_linear.setGeometry(QRect(20, 80, 101, 22))
        self.label_27 = QLabel(self.groupBox_9)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 110, 16, 16))
        self.rod_mount_z_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_z_linear.setObjectName(u"rod_mount_z_linear")
        self.rod_mount_z_linear.setGeometry(QRect(20, 110, 101, 22))
        self.label_28 = QLabel(self.groupBox_9)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 140, 121, 16))
        self.label_29 = QLabel(self.groupBox_9)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 220, 16, 16))
        self.lower_mount_y_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_y_linear.setObjectName(u"lower_mount_y_linear")
        self.lower_mount_y_linear.setGeometry(QRect(20, 190, 101, 22))
        self.lower_mount_z_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_z_linear.setObjectName(u"lower_mount_z_linear")
        self.lower_mount_z_linear.setGeometry(QRect(20, 220, 101, 22))
        self.label_30 = QLabel(self.groupBox_9)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 160, 16, 16))
        self.label_31 = QLabel(self.groupBox_9)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 190, 16, 16))
        self.lower_mount_x_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_x_linear.setObjectName(u"lower_mount_x_linear")
        self.lower_mount_x_linear.setGeometry(QRect(20, 160, 101, 22))
        self.groupBox_10 = QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(150, 20, 131, 251))
        self.linear_travel = QLineEdit(self.groupBox_10)
        self.linear_travel.setObjectName(u"linear_travel")
        self.linear_travel.setGeometry(QRect(20, 50, 101, 22))
        self.label_33 = QLabel(self.groupBox_10)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 30, 121, 16))
        self.screw_pitch = QLineEdit(self.groupBox_10)
        self.screw_pitch.setObjectName(u"screw_pitch")
        self.screw_pitch.setGeometry(QRect(20, 100, 101, 22))
        self.label_34 = QLabel(self.groupBox_10)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 80, 121, 16))
        self.label_36 = QLabel(self.groupBox_10)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 130, 121, 16))
        self.motor_torque_linear = QLineEdit(self.groupBox_10)
        self.motor_torque_linear.setObjectName(u"motor_torque_linear")
        self.motor_torque_linear.setGeometry(QRect(20, 150, 101, 22))
        self.label_37 = QLabel(self.groupBox_10)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 180, 121, 16))
        self.motor_rpm_linear = QLineEdit(self.groupBox_10)
        self.motor_rpm_linear.setObjectName(u"motor_rpm_linear")
        self.motor_rpm_linear.setGeometry(QRect(20, 200, 101, 22))
        self.groupBox_12 = QGroupBox(self.la_tab)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 340, 441, 161))
        self.label_32 = QLabel(self.groupBox_12)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 121, 16))
        self.label_35 = QLabel(self.groupBox_12)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 60, 101, 20))
        self.zx_rodmount_angle_linear = QLineEdit(self.groupBox_12)
        self.zx_rodmount_angle_linear.setObjectName(u"zx_rodmount_angle_linear")
        self.zx_rodmount_angle_linear.setEnabled(False)
        self.zx_rodmount_angle_linear.setGeometry(QRect(170, 30, 61, 22))
        self.zx_pushrod_angle_linear = QLineEdit(self.groupBox_12)
        self.zx_pushrod_angle_linear.setObjectName(u"zx_pushrod_angle_linear")
        self.zx_pushrod_angle_linear.setEnabled(False)
        self.zx_pushrod_angle_linear.setGeometry(QRect(170, 60, 61, 22))
        self.label_43 = QLabel(self.groupBox_12)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 90, 161, 20))
        self.xy_rodmount_pushrod_angle_linear = QLineEdit(self.groupBox_12)
        self.xy_rodmount_pushrod_angle_linear.setObjectName(u"xy_rodmount_pushrod_angle_linear")
        self.xy_rodmount_pushrod_angle_linear.setEnabled(False)
        self.xy_rodmount_pushrod_angle_linear.setGeometry(QRect(170, 90, 61, 22))
        self.button_calc_linear = QPushButton(self.la_tab)
        self.button_calc_linear.setObjectName(u"button_calc_linear")
        self.button_calc_linear.setGeometry(QRect(380, 460, 61, 24))
        self.inputs_tab.addTab(self.la_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1145, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabs.setCurrentIndex(0)
        self.inputs_tab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/images/images/whole_isometric.jpg\"/></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Iso Views", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Front Views", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Top Views", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">While efforts have been made to test this, there could still be bugs and inaccuracies.</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">There could be edge cases that weren't tested. </span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom"
                        ":0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If the input geometry goes into distinctly atypical configurations (such as the ctc and pushrod going past being aligned) the resulting calculations shouldn't be trusted.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Given the nature of how the tool works, all calculations are estimates (that are hopefully acurate to several decimal places).</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">There could be unknown mistakes.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This program is slow, it's normal for it to take 1 or 2 seconds to run.</span></p>\n"
"<p style=\" margin-top:12px; margin-botto"
                        "m:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Take note of the softwares notation and nomenclature. Similar software may look and work similarly but may differ in important ways.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In order to allow more flexible use, neither distance nore force units are assumed. Ensure that the input motor torque is converted appropreately so that it's units of length and force match what's used or desired elsewhere.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Inputs **********************************************************************************************</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block"
                        "-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Rod Mount Position: where the pushrods attach to the seat platform.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">CTC Designs:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Mount Position: the point about which the CTC rotates.</span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Motor Angle: the angle between the CTC and the chassis longnatudinal centerline.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:"
                        "0px; -qt-block-indent:0; text-indent:0px;\">CTC Length: the distance between the motor pivot point and the Push Rod Mount point.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Neutral Angle: the nominal angle of the CTC above the horizontal.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total Rotation: the total amount that the CTC rotates (a value of 45 means that it moves 22.5 degrees in either direction from the nominal position).</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Linear Actuater Designs:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:12px; margi"
                        "n-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Travel: the total travel of the linear actuater (a value of 6 means that it moves 3 units in either direction from the nominal position).</span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pitch: the pitch of the screw used in the actuater.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It's assumed that there's 1:1 gearing between the motor/gearbox output and the screw and that if there's a gearbox, the input torque and RPM is for the gearbox output.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Min &amp; Max CTC Pushrod Angle should never be allowed to toggle"
                        ", go past 0.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Max Torque: an individual motor's max torque with distance units that match what's used elsewhere and force units that are desired in the output plots.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Max RPM: the max RPM of the motors (appropreate unit conversions are done internally).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Outputs ********************************************************************************************</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span styl"
                        "e=\" font-size:10pt;\">All plots represent effects of the contributions of both motors.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">All plots assume that, at the various plotted points, both motors are working together to either puerly pitch, or roll.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The two plot axes of any given plot have the same scale (but different offsets) so designs with equal amounts of pitch and roll will generate square plots, asymetric designs will generate oblong rhombi.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Torque is reported in whatever units are used as force and length.</span></p>\n"
"<p style=\" margin-"
                        "top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Omega is angular speed and is reported in units of degrees / second.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Min &amp; Max CTC Pushrod Angle should never be allowed to toggle, go past 0.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Info", None))
        self.torques_label.setText("")
        self.tabs.setTabText(self.tabs.indexOf(self.torque_tab), QCoreApplication.translate("MainWindow", u"Torques", None))
        self.omegas_label.setText("")
        self.tabs.setTabText(self.tabs.indexOf(self.omega_tab), QCoreApplication.translate("MainWindow", u"Omegas", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Geometry", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Rod Mount Position", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.rod_mount_x_ctc.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.rod_mount_y_ctc.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.rod_mount_z_ctc.setText(QCoreApplication.translate("MainWindow", u"8.5", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Motor Mount Position", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.motor_y.setText(QCoreApplication.translate("MainWindow", u"-8", None))
        self.motor_z.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.motor_x.setText(QCoreApplication.translate("MainWindow", u"45.5", None))
        self.motor_angle.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Motor Angle", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"CTC", None))
        self.ctc_length.setText(QCoreApplication.translate("MainWindow", u"2.5", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Length", None))
        self.ctc_neutral_angle.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Neutral Angle", None))
        self.ctc_rotation.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Total Rotation", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Motor Max Torque", None))
        self.motor_torque_ctc.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Motor Max RPM", None))
        self.motor_rpm_ctc.setText(QCoreApplication.translate("MainWindow", u"70", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Nominal Output Values", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"ZX Rod Mount Angle", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"ZX Pushrod Angle", None))
        self.zx_rodmount_angle_ctc.setText("")
        self.zx_pushrod_angle_ctc.setText("")
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"XY Rodmount Pushrod Angle", None))
        self.xy_rodmount_pushrod_angle_ctc.setText("")
        self.button_calc_ctc.setText(QCoreApplication.translate("MainWindow", u"Calc", None))
        self.min_ctc_pushrod_angle.setText("")
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Min CTC Pushrod Angle", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Max CTC Pushrod Angle", None))
        self.max_ctc_pushrod_angle.setText("")
        self.inputs_tab.setTabText(self.inputs_tab.indexOf(self.ctc_tab), QCoreApplication.translate("MainWindow", u"CTC Based", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Geometry", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Rod Mount Pos.", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.rod_mount_x_linear.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.rod_mount_y_linear.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.rod_mount_z_linear.setText(QCoreApplication.translate("MainWindow", u"8.5", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Actuator Mount Pos.", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.lower_mount_y_linear.setText(QCoreApplication.translate("MainWindow", u"-8", None))
        self.lower_mount_z_linear.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.lower_mount_x_linear.setText(QCoreApplication.translate("MainWindow", u"45.5", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Actuator", None))
        self.linear_travel.setText(QCoreApplication.translate("MainWindow", u"2.5", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Travel", None))
        self.screw_pitch.setText(QCoreApplication.translate("MainWindow", u"0.1968503", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Motor Max Torque", None))
        self.motor_torque_linear.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Motor Max RPM", None))
        self.motor_rpm_linear.setText(QCoreApplication.translate("MainWindow", u"70", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Nominal Output Values", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"ZX Rod Mount Angle", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"ZX Pushrod Angle", None))
        self.zx_rodmount_angle_linear.setText("")
        self.zx_pushrod_angle_linear.setText("")
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"XY Rodmount Pushrod Angle", None))
        self.xy_rodmount_pushrod_angle_linear.setText("")
        self.button_calc_linear.setText(QCoreApplication.translate("MainWindow", u"Calc", None))
        self.inputs_tab.setTabText(self.inputs_tab.indexOf(self.la_tab), QCoreApplication.translate("MainWindow", u"Linear Actuator", None))
    # retranslateUi

