# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

import main_window_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1145, 734)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.speed_tab = QTabWidget(self.centralwidget)
        self.speed_tab.setObjectName(u"speed_tab")
        self.speed_tab.setGeometry(QRect(10, 10, 661, 681))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.whole_iso_label = QLabel(self.tab)
        self.whole_iso_label.setObjectName(u"whole_iso_label")
        self.whole_iso_label.setGeometry(QRect(0, 0, 650, 650))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.whole_iso_label.sizePolicy().hasHeightForWidth())
        self.whole_iso_label.setSizePolicy(sizePolicy1)
        self.whole_iso_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.speed_tab.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_2 = QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 650, 650))
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.speed_tab.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 0, 650, 650))
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.speed_tab.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.textBrowser = QTextBrowser(self.tab_3)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 0, 650, 650))
        self.speed_tab.addTab(self.tab_3, "")
        self.torque_tab = QWidget()
        self.torque_tab.setObjectName(u"torque_tab")
        self.torques_label = QLabel(self.torque_tab)
        self.torques_label.setObjectName(u"torques_label")
        self.torques_label.setGeometry(QRect(0, 0, 650, 650))
        self.torques_label.setAlignment(Qt.AlignCenter)
        self.speed_tab.addTab(self.torque_tab, "")
        self.omega_tab = QWidget()
        self.omega_tab.setObjectName(u"omega_tab")
        self.omegas_label = QLabel(self.omega_tab)
        self.omegas_label.setObjectName(u"omegas_label")
        self.omegas_label.setGeometry(QRect(0, 0, 650, 650))
        self.omegas_label.setAlignment(Qt.AlignCenter)
        self.speed_tab.addTab(self.omega_tab, "")
        self.alpha_tab = QWidget()
        self.alpha_tab.setObjectName(u"alpha_tab")
        self.alphas_label = QLabel(self.alpha_tab)
        self.alphas_label.setObjectName(u"alphas_label")
        self.alphas_label.setGeometry(QRect(0, 0, 650, 650))
        font = QFont()
        font.setPointSize(12)
        self.alphas_label.setFont(font)
        self.alphas_label.setAlignment(Qt.AlignCenter)
        self.speed_tab.addTab(self.alpha_tab, "")
        self.linear_speed_tab = QWidget()
        self.linear_speed_tab.setObjectName(u"linear_speed_tab")
        self.linear_speed_label = QLabel(self.linear_speed_tab)
        self.linear_speed_label.setObjectName(u"linear_speed_label")
        self.linear_speed_label.setGeometry(QRect(0, 0, 650, 650))
        self.linear_speed_label.setFont(font)
        self.linear_speed_label.setAlignment(Qt.AlignCenter)
        self.speed_tab.addTab(self.linear_speed_tab, "")
        self.linear_acc_tab = QWidget()
        self.linear_acc_tab.setObjectName(u"linear_acc_tab")
        self.linear_acc_label = QLabel(self.linear_acc_tab)
        self.linear_acc_label.setObjectName(u"linear_acc_label")
        self.linear_acc_label.setGeometry(QRect(0, 0, 650, 650))
        self.linear_acc_label.setFont(font)
        self.linear_acc_label.setAlignment(Qt.AlignCenter)
        self.speed_tab.addTab(self.linear_acc_tab, "")
        self.inputs_tab = QTabWidget(self.centralwidget)
        self.inputs_tab.setObjectName(u"inputs_tab")
        self.inputs_tab.setGeometry(QRect(680, 10, 461, 621))
        self.ctc_tab = QWidget()
        self.ctc_tab.setObjectName(u"ctc_tab")
        self.groupBox = QGroupBox(self.ctc_tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 441, 331))
        self.groupBox_3 = QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 20, 131, 301))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 121, 16))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 50, 16, 16))
        self.rod_mount_x_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_x_ctc.setObjectName(u"rod_mount_x_ctc")
        self.rod_mount_x_ctc.setGeometry(QRect(20, 50, 101, 22))
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 16, 16))
        self.rod_mount_y_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_y_ctc.setObjectName(u"rod_mount_y_ctc")
        self.rod_mount_y_ctc.setGeometry(QRect(20, 80, 101, 22))
        self.label_7 = QLabel(self.groupBox_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 110, 16, 16))
        self.rod_mount_z_ctc = QLineEdit(self.groupBox_3)
        self.rod_mount_z_ctc.setObjectName(u"rod_mount_z_ctc")
        self.rod_mount_z_ctc.setGeometry(QRect(20, 110, 101, 22))
        self.label_8 = QLabel(self.groupBox_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 140, 121, 16))
        self.label_9 = QLabel(self.groupBox_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 220, 16, 16))
        self.motor_y = QLineEdit(self.groupBox_3)
        self.motor_y.setObjectName(u"motor_y")
        self.motor_y.setGeometry(QRect(20, 190, 101, 22))
        self.motor_z = QLineEdit(self.groupBox_3)
        self.motor_z.setObjectName(u"motor_z")
        self.motor_z.setGeometry(QRect(20, 220, 101, 22))
        self.label_10 = QLabel(self.groupBox_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 160, 16, 16))
        self.label_11 = QLabel(self.groupBox_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 190, 16, 16))
        self.motor_x = QLineEdit(self.groupBox_3)
        self.motor_x.setObjectName(u"motor_x")
        self.motor_x.setGeometry(QRect(20, 160, 101, 22))
        self.motor_angle = QLineEdit(self.groupBox_3)
        self.motor_angle.setObjectName(u"motor_angle")
        self.motor_angle.setGeometry(QRect(20, 270, 101, 22))
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 250, 121, 16))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(150, 20, 131, 301))
        self.ctc_length = QLineEdit(self.groupBox_4)
        self.ctc_length.setObjectName(u"ctc_length")
        self.ctc_length.setGeometry(QRect(20, 50, 101, 22))
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 30, 121, 16))
        self.ctc_neutral_angle = QLineEdit(self.groupBox_4)
        self.ctc_neutral_angle.setObjectName(u"ctc_neutral_angle")
        self.ctc_neutral_angle.setGeometry(QRect(20, 100, 101, 22))
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 80, 121, 16))
        self.ctc_rotation = QLineEdit(self.groupBox_4)
        self.ctc_rotation.setObjectName(u"ctc_rotation")
        self.ctc_rotation.setGeometry(QRect(20, 150, 101, 22))
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 130, 121, 16))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 180, 121, 16))
        self.motor_torque_ctc = QLineEdit(self.groupBox_4)
        self.motor_torque_ctc.setObjectName(u"motor_torque_ctc")
        self.motor_torque_ctc.setGeometry(QRect(20, 200, 101, 22))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 230, 121, 16))
        self.motor_rpm_ctc = QLineEdit(self.groupBox_4)
        self.motor_rpm_ctc.setObjectName(u"motor_rpm_ctc")
        self.motor_rpm_ctc.setGeometry(QRect(20, 250, 101, 22))
        self.groupBox_5 = QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(290, 20, 131, 131))
        self.i_pitch_ctc = QLineEdit(self.groupBox_5)
        self.i_pitch_ctc.setObjectName(u"i_pitch_ctc")
        self.i_pitch_ctc.setGeometry(QRect(20, 50, 101, 22))
        self.label_19 = QLabel(self.groupBox_5)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 30, 121, 16))
        self.i_roll_ctc = QLineEdit(self.groupBox_5)
        self.i_roll_ctc.setObjectName(u"i_roll_ctc")
        self.i_roll_ctc.setGeometry(QRect(20, 100, 101, 22))
        self.label_20 = QLabel(self.groupBox_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 80, 121, 16))
        self.groupBox_7 = QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(290, 160, 131, 131))
        self.pitch_linear_rad_ctc = QLineEdit(self.groupBox_7)
        self.pitch_linear_rad_ctc.setObjectName(u"pitch_linear_rad_ctc")
        self.pitch_linear_rad_ctc.setGeometry(QRect(20, 50, 101, 22))
        self.label_40 = QLabel(self.groupBox_7)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 30, 121, 16))
        self.roll_linear_rad_ctc = QLineEdit(self.groupBox_7)
        self.roll_linear_rad_ctc.setObjectName(u"roll_linear_rad_ctc")
        self.roll_linear_rad_ctc.setGeometry(QRect(20, 100, 101, 22))
        self.label_52 = QLabel(self.groupBox_7)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 80, 121, 16))
        self.groupBox_13 = QGroupBox(self.ctc_tab)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 370, 441, 211))
        self.label_38 = QLabel(self.groupBox_13)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 30, 121, 16))
        self.label_41 = QLabel(self.groupBox_13)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 60, 101, 20))
        self.zx_rodmount_angle_ctc = QLineEdit(self.groupBox_13)
        self.zx_rodmount_angle_ctc.setObjectName(u"zx_rodmount_angle_ctc")
        self.zx_rodmount_angle_ctc.setEnabled(False)
        self.zx_rodmount_angle_ctc.setGeometry(QRect(170, 30, 61, 22))
        self.zx_pushrod_angle_ctc = QLineEdit(self.groupBox_13)
        self.zx_pushrod_angle_ctc.setObjectName(u"zx_pushrod_angle_ctc")
        self.zx_pushrod_angle_ctc.setEnabled(False)
        self.zx_pushrod_angle_ctc.setGeometry(QRect(170, 60, 61, 22))
        self.label_42 = QLabel(self.groupBox_13)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 90, 201, 20))
        self.xy_rodmount_pushrod_angle_ctc = QLineEdit(self.groupBox_13)
        self.xy_rodmount_pushrod_angle_ctc.setObjectName(u"xy_rodmount_pushrod_angle_ctc")
        self.xy_rodmount_pushrod_angle_ctc.setEnabled(False)
        self.xy_rodmount_pushrod_angle_ctc.setGeometry(QRect(170, 90, 61, 22))
        self.button_calc_ctc = QPushButton(self.groupBox_13)
        self.button_calc_ctc.setObjectName(u"button_calc_ctc")
        self.button_calc_ctc.setGeometry(QRect(370, 90, 61, 24))
        self.min_ctc_pushrod_angle = QLineEdit(self.groupBox_13)
        self.min_ctc_pushrod_angle.setObjectName(u"min_ctc_pushrod_angle")
        self.min_ctc_pushrod_angle.setEnabled(False)
        self.min_ctc_pushrod_angle.setGeometry(QRect(370, 60, 61, 22))
        self.label_44 = QLabel(self.groupBox_13)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(240, 60, 131, 16))
        self.label_45 = QLabel(self.groupBox_13)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(240, 30, 131, 16))
        self.max_ctc_pushrod_angle = QLineEdit(self.groupBox_13)
        self.max_ctc_pushrod_angle.setObjectName(u"max_ctc_pushrod_angle")
        self.max_ctc_pushrod_angle.setEnabled(False)
        self.max_ctc_pushrod_angle.setGeometry(QRect(370, 30, 61, 22))
        self.label_46 = QLabel(self.groupBox_13)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 120, 141, 20))
        self.pushrod_length_ctc = QLineEdit(self.groupBox_13)
        self.pushrod_length_ctc.setObjectName(u"pushrod_length_ctc")
        self.pushrod_length_ctc.setEnabled(False)
        self.pushrod_length_ctc.setGeometry(QRect(170, 120, 61, 22))
        self.max_pitch_omega_ctc = QLineEdit(self.groupBox_13)
        self.max_pitch_omega_ctc.setObjectName(u"max_pitch_omega_ctc")
        self.max_pitch_omega_ctc.setEnabled(False)
        self.max_pitch_omega_ctc.setGeometry(QRect(170, 150, 61, 22))
        self.label_48 = QLabel(self.groupBox_13)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(10, 150, 141, 20))
        self.max_roll_omega_ctc = QLineEdit(self.groupBox_13)
        self.max_roll_omega_ctc.setObjectName(u"max_roll_omega_ctc")
        self.max_roll_omega_ctc.setEnabled(False)
        self.max_roll_omega_ctc.setGeometry(QRect(170, 180, 61, 22))
        self.label_49 = QLabel(self.groupBox_13)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 180, 141, 20))
        self.inputs_tab.addTab(self.ctc_tab, "")
        self.la_tab = QWidget()
        self.la_tab.setObjectName(u"la_tab")
        self.groupBox_8 = QGroupBox(self.la_tab)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 0, 441, 301))
        self.groupBox_9 = QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 20, 131, 251))
        self.label_24 = QLabel(self.groupBox_9)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 30, 121, 16))
        self.label_25 = QLabel(self.groupBox_9)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(10, 50, 16, 16))
        self.rod_mount_x_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_x_linear.setObjectName(u"rod_mount_x_linear")
        self.rod_mount_x_linear.setGeometry(QRect(20, 50, 101, 22))
        self.label_26 = QLabel(self.groupBox_9)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(10, 80, 16, 16))
        self.rod_mount_y_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_y_linear.setObjectName(u"rod_mount_y_linear")
        self.rod_mount_y_linear.setGeometry(QRect(20, 80, 101, 22))
        self.label_27 = QLabel(self.groupBox_9)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(10, 110, 16, 16))
        self.rod_mount_z_linear = QLineEdit(self.groupBox_9)
        self.rod_mount_z_linear.setObjectName(u"rod_mount_z_linear")
        self.rod_mount_z_linear.setGeometry(QRect(20, 110, 101, 22))
        self.label_28 = QLabel(self.groupBox_9)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 140, 121, 16))
        self.label_29 = QLabel(self.groupBox_9)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 220, 16, 16))
        self.lower_mount_y_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_y_linear.setObjectName(u"lower_mount_y_linear")
        self.lower_mount_y_linear.setGeometry(QRect(20, 190, 101, 22))
        self.lower_mount_z_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_z_linear.setObjectName(u"lower_mount_z_linear")
        self.lower_mount_z_linear.setGeometry(QRect(20, 220, 101, 22))
        self.label_30 = QLabel(self.groupBox_9)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 160, 16, 16))
        self.label_31 = QLabel(self.groupBox_9)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 190, 16, 16))
        self.lower_mount_x_linear = QLineEdit(self.groupBox_9)
        self.lower_mount_x_linear.setObjectName(u"lower_mount_x_linear")
        self.lower_mount_x_linear.setGeometry(QRect(20, 160, 101, 22))
        self.groupBox_10 = QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(150, 20, 131, 251))
        self.linear_travel = QLineEdit(self.groupBox_10)
        self.linear_travel.setObjectName(u"linear_travel")
        self.linear_travel.setGeometry(QRect(20, 50, 101, 22))
        self.label_33 = QLabel(self.groupBox_10)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 30, 121, 16))
        self.screw_pitch = QLineEdit(self.groupBox_10)
        self.screw_pitch.setObjectName(u"screw_pitch")
        self.screw_pitch.setGeometry(QRect(20, 100, 101, 22))
        self.label_34 = QLabel(self.groupBox_10)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 80, 121, 16))
        self.label_36 = QLabel(self.groupBox_10)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 130, 121, 16))
        self.motor_torque_linear = QLineEdit(self.groupBox_10)
        self.motor_torque_linear.setObjectName(u"motor_torque_linear")
        self.motor_torque_linear.setGeometry(QRect(20, 150, 101, 22))
        self.label_37 = QLabel(self.groupBox_10)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 180, 121, 16))
        self.motor_rpm_linear = QLineEdit(self.groupBox_10)
        self.motor_rpm_linear.setObjectName(u"motor_rpm_linear")
        self.motor_rpm_linear.setGeometry(QRect(20, 200, 101, 22))
        self.groupBox_6 = QGroupBox(self.groupBox_8)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(290, 20, 131, 131))
        self.i_pitch_linear = QLineEdit(self.groupBox_6)
        self.i_pitch_linear.setObjectName(u"i_pitch_linear")
        self.i_pitch_linear.setGeometry(QRect(20, 50, 101, 22))
        self.label_21 = QLabel(self.groupBox_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 30, 121, 16))
        self.i_roll_linear = QLineEdit(self.groupBox_6)
        self.i_roll_linear.setObjectName(u"i_roll_linear")
        self.i_roll_linear.setGeometry(QRect(20, 100, 101, 22))
        self.label_22 = QLabel(self.groupBox_6)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 80, 121, 16))
        self.groupBox_11 = QGroupBox(self.groupBox_8)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(290, 160, 131, 131))
        self.pitch_linear_rad_linear = QLineEdit(self.groupBox_11)
        self.pitch_linear_rad_linear.setObjectName(u"pitch_linear_rad_linear")
        self.pitch_linear_rad_linear.setGeometry(QRect(20, 50, 101, 22))
        self.label_53 = QLabel(self.groupBox_11)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 30, 121, 16))
        self.roll_linear_rad_linear = QLineEdit(self.groupBox_11)
        self.roll_linear_rad_linear.setObjectName(u"roll_linear_rad_linear")
        self.roll_linear_rad_linear.setGeometry(QRect(20, 100, 101, 22))
        self.label_54 = QLabel(self.groupBox_11)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 80, 121, 16))
        self.groupBox_12 = QGroupBox(self.la_tab)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 370, 441, 211))
        self.label_32 = QLabel(self.groupBox_12)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 30, 121, 16))
        self.label_35 = QLabel(self.groupBox_12)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 60, 101, 20))
        self.zx_rodmount_angle_linear = QLineEdit(self.groupBox_12)
        self.zx_rodmount_angle_linear.setObjectName(u"zx_rodmount_angle_linear")
        self.zx_rodmount_angle_linear.setEnabled(False)
        self.zx_rodmount_angle_linear.setGeometry(QRect(170, 30, 61, 22))
        self.zx_pushrod_angle_linear = QLineEdit(self.groupBox_12)
        self.zx_pushrod_angle_linear.setObjectName(u"zx_pushrod_angle_linear")
        self.zx_pushrod_angle_linear.setEnabled(False)
        self.zx_pushrod_angle_linear.setGeometry(QRect(170, 60, 61, 22))
        self.label_43 = QLabel(self.groupBox_12)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 90, 161, 20))
        self.xy_rodmount_pushrod_angle_linear = QLineEdit(self.groupBox_12)
        self.xy_rodmount_pushrod_angle_linear.setObjectName(u"xy_rodmount_pushrod_angle_linear")
        self.xy_rodmount_pushrod_angle_linear.setEnabled(False)
        self.xy_rodmount_pushrod_angle_linear.setGeometry(QRect(170, 90, 61, 22))
        self.nominal_pushrod_length_linear = QLineEdit(self.groupBox_12)
        self.nominal_pushrod_length_linear.setObjectName(u"nominal_pushrod_length_linear")
        self.nominal_pushrod_length_linear.setEnabled(False)
        self.nominal_pushrod_length_linear.setGeometry(QRect(170, 120, 61, 22))
        self.label_47 = QLabel(self.groupBox_12)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(10, 120, 141, 20))
        self.max_pitch_omega_linear = QLineEdit(self.groupBox_12)
        self.max_pitch_omega_linear.setObjectName(u"max_pitch_omega_linear")
        self.max_pitch_omega_linear.setEnabled(False)
        self.max_pitch_omega_linear.setGeometry(QRect(170, 150, 61, 22))
        self.label_50 = QLabel(self.groupBox_12)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(10, 180, 141, 20))
        self.max_roll_omega_linear = QLineEdit(self.groupBox_12)
        self.max_roll_omega_linear.setObjectName(u"max_roll_omega_linear")
        self.max_roll_omega_linear.setEnabled(False)
        self.max_roll_omega_linear.setGeometry(QRect(170, 180, 61, 22))
        self.label_51 = QLabel(self.groupBox_12)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(10, 150, 141, 20))
        self.button_calc_linear = QPushButton(self.la_tab)
        self.button_calc_linear.setObjectName(u"button_calc_linear")
        self.button_calc_linear.setGeometry(QRect(380, 430, 61, 24))
        self.inputs_tab.addTab(self.la_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1145, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.speed_tab.setCurrentIndex(0)
        self.inputs_tab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.whole_iso_label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/images/images/whole_isometric.png\"/></p></body></html>", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Iso Views", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/images/images/front_view.png\"/></p></body></html>", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Front Views", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><img src=\":/images/images/top_view.png\"/></p></body></html>", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Top Views", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">While efforts have been made to test this, there could still be bugs and inaccuracies.</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">There could be edge cases that weren't tested. </span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom"
                        ":0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If the input geometry goes into distinctly atypical configurations (such as the ctc and pushrod going past being aligned) the resulting calculations shouldn't be trusted.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Given the nature of how the tool works, all calculations are estimates (that are hopefully accurate to several decimal places).</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">There could be unknown mistakes.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This program is slow, it's normal for it to take 1 or 2 seconds to run.</span></p>\n"
"<p style=\" margin-top:12px; margin-bott"
                        "om:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Take note of the software's notation and nomenclature. Similar software may look and work similarly but may differ in important ways.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">In order to allow more flexible use, neither distance nor force units are assumed. Ensure that the input motor torque is converted appropriately so that it's units of length and force match what's used or desired elsewhere.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Inputs **********************************************************************************************</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-bloc"
                        "k-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Rod Mount Position: where the pushrods attach to the seat platform. Measured with respect to the under rocker platform pivot.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">CTC Designs:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Mount Position: the point about which the CTC rotates. Measured from the main rocker platform pivot.</span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Motor Angle: the angle between the CTC and the chassis longitudinal centerline.</li>\n"
"<"
                        "li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CTC Length: the distance between the motor pivot point and the Push Rod Mount point.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Neutral Angle: the nominal angle of the CTC above the horizontal.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total Rotation: the total amount that the CTC rotates (a value of 45 means that it moves 22.5 degrees in either direction from the nominal position).</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Linear Actuator Designs:</span></p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; m"
                        "argin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\"\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Travel: the total travel of the linear actuator (a value of 6 means that it moves 3 units in either direction from the nominal position).</span></li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pitch: the pitch of the screw used in the actuator.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">It's assumed that there's 1:1 gearing between the motor/gearbox output and the screw and that if there's a gearbox, the input torque and RPM is for the gearbox output.</li>\n"
"<li style=\" font-size:10pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; "
                        "-qt-block-indent:0; text-indent:0px;\">Min &amp; Max CTC Pushrod Angle should never be allowed to toggle, go past 0.</li></ul>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Max Torque: an individual motor's max torque with distance units that match what's used elsewhere and force units that are desired in the output plots.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Motor Max RPM: the max RPM of the motors (appropriate unit conversions are done internally).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">I Pitch: the mass moment of inertia about the z axis (pitch inertia).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left"
                        ":0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">I Roll: the mass moment of inertia about the x axis (roll inertia).</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Pitch Inspect. Rad.: the length from the pitch axis to a point of interest for which linear values are to be calculated in the pitch direction.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Roll Inspect. Rad.: the length from the roll axis to a point of interest for which linear values are to be calculated in the roll direction.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Outputs *******************************************************"
                        "*************************************</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">All plots represent effects of the contributions of both motors.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">All plots assume that, at the various plotted points, both motors are working together to either purely pitch, or roll.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The two plot axes of any given plot have the same scale (but different offsets) so designs with equal amounts of pitch and roll will generate square plots, asymmetric designs will generate oblong rhombi.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; marg"
                        "in-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Torque is reported in whatever units are used as force and length.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Omega is angular speed and is reported in units of degrees / second.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Alpha is angular acceleration and is reported in units of degrees / second squared.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Min &amp; Max CTC Pushrod Angle should never be allowed to toggle, go past 0.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-inde"
                        "nt:0px;\"><span style=\" font-size:10pt;\">Max Pitch and Roll Omega are the max achievable speed if accelerated with the max torqu through all of the pitch or roll range of motion. Uses a constant torque equal to that of the torque when pitch and roll positions are both 0 degrees. Represents the max possible values.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Since pitch and roll omega plots represent the speed at that position given the motors' input RPM, if the value is higher than the &quot;Max Pitch Omega&quot; or &quot;Max Roll Omega&quot; respectively, then that the plotted speed is unachivable so it may make sense to change geometry so that lower omegas but higher alphas are plotted.</span></p></body></html>", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Info", None))
        self.torques_label.setText("")
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.torque_tab), QCoreApplication.translate("MainWindow", u"Torques", None))
        self.omegas_label.setText("")
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.omega_tab), QCoreApplication.translate("MainWindow", u"Omegas", None))
        self.alphas_label.setText(QCoreApplication.translate("MainWindow", u"This is only meaningfull if accurate values are entered for \"I Pitch\" and \"I Roll\"", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.alpha_tab), QCoreApplication.translate("MainWindow", u"Alphas", None))
        self.linear_speed_label.setText(QCoreApplication.translate("MainWindow", u"This is only meaningfull if accurate values are entered for \"I Pitch\" and \"I Roll\"", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.linear_speed_tab), QCoreApplication.translate("MainWindow", u"Linear Speed", None))
        self.linear_acc_label.setText(QCoreApplication.translate("MainWindow", u"This is only meaningfull if accurate values are entered for \"I Pitch\" and \"I Roll\"", None))
        self.speed_tab.setTabText(self.speed_tab.indexOf(self.linear_acc_tab), QCoreApplication.translate("MainWindow", u"Linear Acc.", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Geometry", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Rod Mount Position", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.rod_mount_x_ctc.setText(QCoreApplication.translate("MainWindow", u"19.5", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.rod_mount_y_ctc.setText(QCoreApplication.translate("MainWindow", u"28.5", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.rod_mount_z_ctc.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Motor Mount Position", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.motor_y.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.motor_z.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.motor_x.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.motor_angle.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Motor Angle", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"CTC", None))
        self.ctc_length.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Length", None))
        self.ctc_neutral_angle.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Neutral Angle", None))
        self.ctc_rotation.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Total Rotation", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Motor Max Torque", None))
        self.motor_torque_ctc.setText(QCoreApplication.translate("MainWindow", u"400", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Motor Max RPM", None))
        self.motor_rpm_ctc.setText(QCoreApplication.translate("MainWindow", u"70", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Moment of Inertia", None))
        self.i_pitch_ctc.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"I Pitch", None))
        self.i_roll_ctc.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"I Roll", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Linear Inputs", None))
        self.pitch_linear_rad_ctc.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Pitch Inspect. Rad.", None))
        self.roll_linear_rad_ctc.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Roll Inspect. Rad.", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Nominal Output Values", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"ZX Rod Mount Angle", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"ZX Pushrod Angle", None))
        self.zx_rodmount_angle_ctc.setText("")
        self.zx_pushrod_angle_ctc.setText("")
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"XY Rodmount Pushrod Angle", None))
        self.xy_rodmount_pushrod_angle_ctc.setText("")
        self.button_calc_ctc.setText(QCoreApplication.translate("MainWindow", u"Calc", None))
        self.min_ctc_pushrod_angle.setText("")
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Min CTC Pushrod Angle", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Max CTC Pushrod Angle", None))
        self.max_ctc_pushrod_angle.setText("")
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Pushrod Length", None))
        self.pushrod_length_ctc.setText("")
        self.max_pitch_omega_ctc.setText("")
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Max Pitch Omega", None))
        self.max_roll_omega_ctc.setText("")
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Max Roll Omega", None))
        self.inputs_tab.setTabText(self.inputs_tab.indexOf(self.ctc_tab), QCoreApplication.translate("MainWindow", u"CTC Based", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Inputs", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Geometry", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Rod Mount Pos.", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.rod_mount_x_linear.setText(QCoreApplication.translate("MainWindow", u"23", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.rod_mount_y_linear.setText(QCoreApplication.translate("MainWindow", u"28", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.rod_mount_z_linear.setText(QCoreApplication.translate("MainWindow", u"8.5", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Actuator Mount Pos.", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.lower_mount_y_linear.setText(QCoreApplication.translate("MainWindow", u"-8", None))
        self.lower_mount_z_linear.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.lower_mount_x_linear.setText(QCoreApplication.translate("MainWindow", u"45.5", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Actuator", None))
        self.linear_travel.setText(QCoreApplication.translate("MainWindow", u"2.5", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Travel", None))
        self.screw_pitch.setText(QCoreApplication.translate("MainWindow", u"0.1968503", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Motor Max Torque", None))
        self.motor_torque_linear.setText(QCoreApplication.translate("MainWindow", u"0.40", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Motor Max RPM", None))
        self.motor_rpm_linear.setText(QCoreApplication.translate("MainWindow", u"3500", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Moment of Inertia", None))
        self.i_pitch_linear.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"I Pitch", None))
        self.i_roll_linear.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"I Roll", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Linear Inputs", None))
        self.pitch_linear_rad_linear.setText(QCoreApplication.translate("MainWindow", u"50", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Pitch Inspect. Rad.", None))
        self.roll_linear_rad_linear.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Roll Inspect. Rad.", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Nominal Output Values", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"ZX Rod Mount Angle", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"ZX Pushrod Angle", None))
        self.zx_rodmount_angle_linear.setText("")
        self.zx_pushrod_angle_linear.setText("")
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"XY Rodmount Pushrod Angle", None))
        self.xy_rodmount_pushrod_angle_linear.setText("")
        self.nominal_pushrod_length_linear.setText("")
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Nominal Pushrod Length", None))
        self.max_pitch_omega_linear.setText("")
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Max Roll Omega", None))
        self.max_roll_omega_linear.setText("")
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Max Pitch Omega", None))
        self.button_calc_linear.setText(QCoreApplication.translate("MainWindow", u"Calc", None))
        self.inputs_tab.setTabText(self.inputs_tab.indexOf(self.la_tab), QCoreApplication.translate("MainWindow", u"Linear Actuator", None))
    # retranslateUi

